### ISSUE TITLE
render a small version

### ISSUE THREAD

**Issue by al3rez** [seletskiy/monaco-font#1]
Hey, your font is awesome! would you render a small version (10 pt)? take a look at this [screenshot](https://camo.githubusercontent.com/0326eed0732a1782a2d512f961d4edd96328c9ca/687474703a2f2f6e616e6f746563682e6e616e6f74656368636f72702e6e65742f646f776e6c6f6164732f6a656c6c796265616e732d707265766965772e706e67).

**Comment by seletskiy** [comment]
@fujinuma: I don't sure I will render it, because, actually, it's handdrawn.

**Comment by al3rez** [comment]
don't bother. now I've got a new monitor :smiley:

**Comment by seletskiy** [comment]
@fujinuma: :+1:

Do you still use my font?
