### ISSUE TITLE
Bold font rendering in urxvt

### ISSUE THREAD

**Issue by 97-109-107** [seletskiy/monaco-font#2]
![here](https://0x0.st/qSm.png) 
As visible above, when using the following font declarations in Xresources:

```
URxvt.font:      xft:Monaco:pixelsize=12:antialias=false:hinting=false,
URxvt.boldFont:  xft:Monaco:bold:pixelsize=12:antialias=false:hinting=false,
URxvt.letterSpace: 0
URxvt.lineSpace: 1
```

Most bold glyphs appear to chopped from the left side (as if they were too wide).

Is this an issue with the font or URxvt? 

I see that setting letterspace to 1 alleviates the issue, but does that mean that setting it to 0 is incorrect?

**Comment by seletskiy** [comment]
@97-109-107: Your bold fonts does not looks like monaco bold typeface, more looks like it's automatically generated bold typeface.

That's how it looks like:
![2016-05-18-10t04t44](https://cloud.githubusercontent.com/assets/674812/15347109/3df746cc-1ce0-11e6-940a-eac55ef4fcdc.png)

I do use following records in `~/.Xresources`:

```
URxvt.font: xft:Monaco:pixelsize=12:antialias=false
URxvt.boldFont: xft:Monaco:style=Bold:pixelsize=12:antialias=false
URxvt.italicFont:
URxvt.boldItalicFont:
URxvt.letterSpace: 0
URxvt.lineSpace: 0
```

**Comment by seletskiy** [comment]
@97-109-107: Do you like it?

**Comment by 97-109-107** [comment]
I absolutely love it. It has the curviness of 
[Luculent](http://eastfarthing.com/luculent/) while being bitmap-crisp.

![ pic ](https://0x0.st/qe8.png)

Thanks!

**Comment by seletskiy** [comment]
@97-109-107: good! Glad someone else likes it.
